### ISSUE TITLE
Consider a slightly more explicit style for early instructions in a guide

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/guide-microprofile-intro#22]
In these lines:

"First, create the JAX-RS service that serves as the systems endpoint:
src/main/java/io/openliberty/guides/microprofile/InventoryResource.java
[code snippet to paste in]"

Two people misunderstood this step and weren't sure what they were supposed to do to create the JAX-RS service (neither experienced in Java but one was a non-Java developer in the past). I think maybe the first 'copy-and-paste-this-snippet' step needs to be more explicit in each guide. eg:

"First, create the JAX-RS service that serves as the systems endpoint. To do this, create an empty file with this file name and paste the following code into it, then save the file:
src/main/java/io/openliberty/guides/microprofile/InventoryResource.java
[code snippet to paste in]"

If we can get the wording of the first step right (and fix issue #21), I think the rest of the steps will be clear enough.

We should test the new wording before pushing to live.

**Comment by yeekangc** [comment]
@sishida, can you please take a look at this?

**Comment by sishida** [comment]
@yeekangc: Hi! Could you please include a link to the file that has been changed?

Also, on a related note, maybe we should consider how we want to handle these Open Liberty defects going forward. I was going to add an "ID Required" label or something similar, but I didn't see one as an option here.

@chirp1 Karen, do you have some ideas for how you think we should handle Open Liberty defects like this?

Thank you both!

**Comment by sishida** [comment]
@yeekangc: I found the file! :) (I'm still getting used to GitHub.) I created a pull request for my changes: https://github.com/OpenLiberty/guide-microprofile-intro/pull/24

I wasn't sure who would review it, so I assigned both you and @lauracowen. Please let me know if you would like additional changes. Thank you!

**Comment by chirp1** [comment]
@yeekangc @sishida YK and I have been chatting about what to do over sametime about how we can aggregate the work items. As an FYI.... I have been looking into what to do about adding labels. I believe the problem is that the code and doc are in separate repositories for each guide. These guides are also in separate repositories form the main repository of open-liberty. In the open-liberty repository we have labels for "ID required" (more for messages) and "documentation required" that I added last night, for general documentation. However, when somebody creates a repository, these labels don't see mto carry over. From googling, There might be an option to filter across repositories: https://github.com/blog/1901-managing-issues-and-pull-requests-across-repositories . However, we might then have to add labels and the like to each repository as we create more repositories. I also found from googling that  some teams use a main repository to track issues across multiple repositories, such as all these repositories for these guides. YK, in our sametime thought that people would continue to create issues in their individual repositories. I can set up a meeting for us to discuss further.

**Comment by sishida** [comment]
@chirp1: Do you think we could add the defects to one of the meetings that already exists for Open Liberty, such as the "Liberty docs - open vs. closed" or the weekly Open Liberty meeting?

**Comment by sishida** [comment]
@yeekangc and @lauracowen: Hi, team, Is this defect good to close? If so, could we please merge the changes from the pull request and close? If not, could you please let me know how I can continue working on it? Thank you!

**Comment by lauracowen** [comment]
Can you leave it open for now? I need to go back and review the whole guide based on what we've done in the REST guide. Feel free to assign this issue to me if that helps.

**Comment by evelinec** [comment]
This guide had been archived.
