### ISSUE TITLE
Test cases are not independent from each other

### ISSUE THREAD

**Issue by JunyiSun** [OpenLiberty/guide-microprofile-intro#23]
In the `EndPointTest.java`, if we comment out one test case such as 
```
@Test
    public void testSuite() {
        this.testEmptyInventory();
        // this.testHostRegistration();
        this.testSystemPropertiesMatch();
        this.testUnknownHost();
    }
```
Then run `mvn clean install` again,  the following test case will fail. 
Although if we run all 4 test cases together, they will all pass.
It means that each test case is not independent, which is an issue.

**Comment by Kubik42** [comment]
This is intentional. Hosts that are registered are used in later tests. I dont think we really need to worry about this too much.

- `testHostRegistration` registers and hosts and tests that registration was successful
- `testSystemPropertiesMatch` retrieves the system properties of the registered host from the inventory and attempts to match them against the ones available at the `System` service running on that host

**Comment by Ahmad-Ayyoub** [comment]
I have investigated the tests and yeah I have remembered doing the tests in this way. You are right @Kubik42. However, we can still fix this as I did in the PR. Have a look please:

https://github.com/OpenLiberty/guide-microprofile intro/pull/25/commits/4912a27dacfb18ccd4c8268df2dd8ae2ec26d12e

**Comment by yeekangc** [comment]
If order is assumed or required, we shall need them clear.

**Comment by Ahmad-Ayyoub** [comment]
Shall we specify that as a comment or in the guide adoc. ?

**Comment by Kubik42** [comment]
We use the test suite for a reason - to force the order of tests execution. It is already mentioned in the guide. I think its best we leave it as is since other guides use test suites like this one as well.
