### ISSUE TITLE
Archive MP Intro guide

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-intro#43]
This MP Intro is now superseded by the combination of the REST Intro and CDI Intro guides.

We should archive this guide.  Should check that after it is archived, it won't show up on searches on openliberty.io.  Then, direct URL access should still return the guide should it has been bookmarked.

Should have a banner to redirect to new(er) guides too.

**Comment by lauracowen** [comment]
I think this should be a permanent redirect (rather than a manual redirect and banner). Otherwise we'll have loads of old content floating around being searched by Google (etc) and potentially being returned when we want the focus (and google juice) to be on the new guides.

I appreciate the point about the MP guide being now represented by two guides (REST and CDI) but I think we should try to be good about taking old/redundant content away rather than letting everything just build up and making people do additional clicks when we don't really want people to be visiting the old guides at all if at all.

The CDI guide was a re-write of the MP guide (with much the same content) to make it more focused after various discussions around what it was trying to show (eg #37). I agree people might come looking for the JAX-RS part of the MP guide but it wouldn't be that difficult for them to find the REST guide (once on the site) if that's what they needed.

Alternatively, we just redirect to the REST guide instead of the CDI guide. But I think we should make that decision. I doubt it'll affect masses of users anyway. And anyone searching for MicroProfile would (I'd imagine/hope?) find our many other MP guides (esp when we have a category and intro for the category anyway).

**Comment by evelinec** [comment]
Consulted @steven1046 that applying a tag to the readme.adoc file will hide the guide on the website; tested it on the test site. The original URL is still accessible.

**Comment by evelinec** [comment]
@steven1046 added the redirection for the mp-intro to the cd-intro guide.

**Comment by evelinec** [comment]
This task is complete. @yeekangc and @lauracowen can you review?

**Comment by evelinec** [comment]
Still working on archiving the repo.

**Comment by evelinec** [comment]
Archive note is added to the repo in #50.
